import { createClient } from '@/lib/supabase/server'
import type { AssessmentExport, AssessmentResult } from '@/lib/types/assessment'

/**
 * Assessment Export Service
 * Handles exporting assessment results as PDF and shareable links
 */

export interface ExportData {
  userId: string
  assessmentId: string
  format: 'pdf' | 'json'
  includeInterpretation: boolean
  shareableLink?: boolean
  expiresIn?: number // days
}

export class AssessmentExportService {
  private supabase = createClient()

  /**
   * Create export record
   */
  async createExport(data: ExportData): Promise<AssessmentExport> {
    const expiresAt = data.expiresIn
      ? new Date(Date.now() + data.expiresIn * 24 * 60 * 60 * 1000).toISOString()
      : null

    const { data: exportRecord, error } = await this.supabase
      .from('assessment_exports')
      .insert({
        user_id: data.userId,
        assessment_id: data.assessmentId,
        format: data.format,
        include_interpretation: data.includeInterpretation,
        shareable_link: data.shareableLink,
        expires_at: expiresAt,
      })
      .select()
      .single()

    if (error) throw error
    return exportRecord
  }

  /**
   * Get export record
   */
  async getExport(exportId: string): Promise<AssessmentExport | null> {
    const { data, error } = await this.supabase
      .from('assessment_exports')
      .select('*')
      .eq('id', exportId)
      .single()

    if (error && error.code === 'PGRST116') {
      return null
    }
    if (error) throw error

    // Check if expired
    if (data.expires_at && new Date(data.expires_at) < new Date()) {
      return null
    }

    return data
  }

  /**
   * List exports for user
   */
  async listExports(userId: string): Promise<AssessmentExport[]> {
    const { data, error } = await this.supabase
      .from('assessment_exports')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })

    if (error) throw error

    // Filter out expired exports
    return (data || []).filter(
      (exp) => !exp.expires_at || new Date(exp.expires_at) > new Date()
    )
  }

  /**
   * Generate PDF content from assessment result
   */
  generatePDFContent(result: AssessmentResult, includeInterpretation: boolean): string {
    let content = `
ASSESSMENT REPORT
=================

Date: ${new Date(result.created_at).toLocaleDateString()}
Assessment Type: ${result.assessment_type}

SCORES
------
${Object.entries(result.scores)
  .map(([key, value]) => `${key}: ${value}`)
  .join('\n')}
    `

    if (includeInterpretation && result.interpretation) {
      content += `

INTERPRETATION
---------------
${result.interpretation}
    `
    }

    content += `

CONFIDENTIALITY NOTICE
---------------------
This assessment is confidential and intended only for the individual and their healthcare providers.
Do not share without consent.

Generated by NeuRafiki
Part of the African Neurodiversity Alliance
    `

    return content
  }

  /**
   * Generate shareable token
   */
  generateShareableToken(): string {
    return `export_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
  }

  /**
   * Revoke export sharing
   */
  async revokeExport(exportId: string, userId: string): Promise<void> {
    const { error } = await this.supabase
      .from('assessment_exports')
      .update({ shareable_link: false })
      .eq('id', exportId)
      .eq('user_id', userId)

    if (error) throw error
  }

  /**
   * Log export download
   */
  async logExportDownload(exportId: string, ipAddress: string): Promise<void> {
    const { error } = await this.supabase
      .from('assessment_exports')
      .update({
        last_accessed_at: new Date().toISOString(),
        download_count: this.supabase.rpc('increment_download_count', {
          export_id: exportId,
        }),
      })
      .eq('id', exportId)

    if (error) throw error
  }

  /**
   * Create professional report for healthcare providers
   */
  async createProfessionalReport(
    assessmentId: string,
    userId: string,
    providerEmail: string
  ): Promise<AssessmentExport> {
    // Verify assessment ownership
    const { data: assessment, error: fetchError } = await this.supabase
      .from('assessment_results')
      .select('*')
      .eq('id', assessmentId)
      .eq('user_id', userId)
      .single()

    if (fetchError) throw fetchError

    const exportRecord = await this.createExport({
      userId,
      assessmentId,
      format: 'pdf',
      includeInterpretation: true,
      shareableLink: true,
      expiresIn: 30, // 30-day validity for professional reports
    })

    // TODO: Send email to provider with access link
    // sendProfessionalReportEmail(providerEmail, assessment, exportRecord)

    return exportRecord
  }

  /**
   * Clean up expired exports
   */
  async cleanupExpiredExports(): Promise<number> {
    const { data, error } = await this.supabase
      .from('assessment_exports')
      .delete()
      .lt('expires_at', new Date().toISOString())
      .select()

    if (error) throw error
    return data?.length || 0
  }
}

export const assessmentExportService = new AssessmentExportService()
