-- Seed comprehensive assessment questions based on pasted-text-4 breakdown
-- Total: ~838 main assessment questions + follow-up questions

-- First, insert the comprehensive assessment domains
INSERT INTO assessment_domains (name, code, age_group, age_min, age_max, question_count, description, cultural_adaptations) VALUES
-- Toddlers (2-5 years) - Total: 120 questions
('Autism Spectrum (Toddlers)', 'autism_toddler', 'toddler', 2, 5, 20, 'M-CHAT-R/F and GARS-3 inspired screening for autism spectrum traits in toddlers', '{"african_context": true, "cultural_examples": ["extended family interactions", "community gatherings", "traditional play"]}'),
('ADHD (Toddlers)', 'adhd_toddler', 'toddler', 2, 5, 25, 'Vanderbilt and Conners inspired attention and hyperactivity screening for toddlers', '{"african_context": true, "cultural_examples": ["market visits", "family chores", "storytelling sessions"]}'),
('Sensory Processing (Toddlers)', 'sensory_toddler', 'toddler', 2, 5, 60, 'Sensory Profile 2 inspired assessment for sensory sensitivities and preferences', '{"african_context": true, "cultural_examples": ["traditional music", "textured foods", "natural environments"]}'),
('Motor Coordination (Toddlers)', 'motor_toddler', 'toddler', 2, 5, 15, 'DCDQ inspired motor coordination and dyspraxia screening', '{"african_context": true, "cultural_examples": ["traditional dances", "carrying objects", "climbing activities"]}'),

-- Children/Adolescents (6-18 years) - Total: 372 questions
('Autism Spectrum (Children)', 'autism_child', 'child_adolescent', 6, 18, 65, 'SRS and GARS-3 inspired comprehensive autism spectrum assessment', '{"african_context": true, "cultural_examples": ["school interactions", "peer relationships", "family responsibilities"]}'),
('ADHD (Children)', 'adhd_child', 'child_adolescent', 6, 18, 55, 'Conners 3 and Vanderbilt inspired ADHD assessment for children and adolescents', '{"african_context": true, "cultural_examples": ["classroom behavior", "homework completion", "chore responsibilities"]}'),
('Learning Differences (Children)', 'learning_child', 'child_adolescent', 6, 18, 60, 'CTOPP-2 and WRAT-5 inspired dyslexia and learning differences assessment', '{"african_context": true, "cultural_examples": ["local language reading", "math in local currency", "cultural stories"]}'),
('Motor Coordination (Children)', 'motor_child', 'child_adolescent', 6, 18, 20, 'Dyspraxia and motor coordination assessment for school-age children', '{"african_context": true, "cultural_examples": ["sports activities", "handwriting", "traditional crafts"]}'),
('Sensory Processing (Children)', 'sensory_child', 'child_adolescent', 6, 18, 86, 'Comprehensive sensory processing assessment for children and adolescents', '{"african_context": true, "cultural_examples": ["school environment", "community noise", "traditional ceremonies"]}'),
('Executive Function (Children)', 'executive_child', 'child_adolescent', 6, 18, 86, 'BRIEF-2 inspired executive function assessment', '{"african_context": true, "cultural_examples": ["planning school projects", "managing time", "following multi-step instructions"]}'),

-- Adults (18+) - Total: 286 questions
('Autism Spectrum (Adults)', 'autism_adult', 'adult', 18, 100, 50, 'AQ inspired autism spectrum assessment for adults', '{"african_context": true, "cultural_examples": ["workplace interactions", "community roles", "family responsibilities"]}'),
('ADHD (Adults)', 'adhd_adult', 'adult', 18, 100, 45, 'Adult ADHD self-report assessment', '{"african_context": true, "cultural_examples": ["work performance", "time management", "relationship management"]}'),
('Learning Differences (Adults)', 'learning_adult', 'adult', 18, 100, 25, 'Adult dyslexia and learning differences assessment', '{"african_context": true, "cultural_examples": ["reading documents", "writing reports", "numerical tasks"]}'),
('Motor Coordination (Adults)', 'motor_adult', 'adult', 18, 100, 20, 'Adult dyspraxia and motor coordination assessment', '{"african_context": true, "cultural_examples": ["fine motor tasks", "coordination activities", "daily living skills"]}'),
('Sensory Processing (Adults)', 'sensory_adult', 'adult', 18, 100, 60, 'Adult sensory processing assessment', '{"african_context": true, "cultural_examples": ["work environment", "social gatherings", "daily routines"]}'),
('Executive Function (Adults)', 'executive_adult', 'adult', 18, 100, 86, 'Adult executive function assessment', '{"african_context": true, "cultural_examples": ["work planning", "financial management", "household organization"]}');

-- Sample comprehensive questions for Autism Spectrum (Toddlers) - 20 questions
INSERT INTO assessment_questions (domain_id, question_text, question_type, response_options, age_group, respondent_type, cultural_context, order_index) VALUES
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child enjoy playing with other children in your community or extended family?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Consider extended family and community interactions common in African contexts"}', 1),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child point to show you something interesting, like pointing to an airplane or big truck?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Adapt examples to local context - matatu, traditional ceremonies, animals"}', 2),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child respond when you call their name from across the room?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 3),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child show unusual interest in spinning objects, wheels, or repetitive movements?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 4),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child make eye contact when you are talking or playing with them?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Consider cultural norms around eye contact with adults"}', 5),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child imitate you when you clap your hands or wave goodbye?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Include traditional greetings and gestures"}', 6),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child bring objects to show you (not just to get help, but to share interest)?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 7),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child seem to understand simple instructions like "come here" or "give me"?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Consider instructions in local language"}', 8),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child walk steadily without support?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 9),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child look at things when you point and say "look at..."?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 10),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child play pretend games, like feeding a doll or talking on a toy phone?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Adapt to local toys and pretend play scenarios"}', 11),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child seem overly sensitive to sounds, like covering ears during traditional music or ceremonies?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Include traditional music and ceremony contexts"}', 12),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child have difficulty with changes in routine or unexpected events?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 13),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child repeat words or phrases over and over?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 14),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child have trouble sleeping or unusual sleep patterns?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 15),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child show interest in other children but not know how to play with them?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 16),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child have strong reactions to certain textures, foods, or clothing?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{"cultural_notes": "Consider traditional foods and clothing textures"}', 17),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child line up toys or objects in a specific order repeatedly?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 18),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child seem to understand emotions in others (happy, sad, angry)?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 19),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Does your child engage in back-and-forth conversation or babbling with you?', 'yes_no', '{"options": [{"value": 0, "label": "No"}, {"value": 1, "label": "Yes"}]}', 'toddler', 'parent', '{}', 20);

-- Sample questions for ADHD (Children) - First 10 of 55 questions
INSERT INTO assessment_questions (domain_id, question_text, question_type, response_options, age_group, respondent_type, cultural_context, order_index) VALUES
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child have difficulty paying attention to tasks or play activities?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{"cultural_notes": "Consider both school and home responsibilities"}', 1),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child make careless mistakes in schoolwork or other activities?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 2),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child have difficulty sustaining attention during tasks or play?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 3),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child seem not to listen when spoken to directly?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{"cultural_notes": "Consider cultural expectations for child attention to adults"}', 4),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child fail to follow through on instructions and fail to finish schoolwork or chores?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{"cultural_notes": "Include both school and household responsibilities"}', 5),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child have difficulty organizing tasks and activities?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 6),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child avoid or dislike tasks that require sustained mental effort?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 7),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often does your child lose things necessary for tasks or activities?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 8),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often is your child easily distracted by external stimuli?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 9),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'How often is your child forgetful in daily activities?', 'likert', '{"options": [{"value": 0, "label": "Never"}, {"value": 1, "label": "Rarely"}, {"value": 2, "label": "Sometimes"}, {"value": 3, "label": "Often"}, {"value": 4, "label": "Very Often"}]}', 'child_adolescent', 'parent', '{}', 10);

-- Sample follow-up questions for longitudinal monitoring
INSERT INTO assessment_questions (domain_id, question_text, question_type, response_options, age_group, respondent_type, cultural_context, order_index, is_follow_up, baseline_question_id) VALUES
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'Since our last assessment, has your child shown improvement in playing with other children?', 'scale', '{"options": [{"value": 0, "label": "Much Worse"}, {"value": 1, "label": "Worse"}, {"value": 2, "label": "No Change"}, {"value": 3, "label": "Better"}, {"value": 4, "label": "Much Better"}]}', 'toddler', 'parent', '{"follow_up_type": "progress_tracking"}', 1, true, (SELECT id FROM assessment_questions WHERE domain_id = (SELECT id FROM assessment_domains WHERE code = 'autism_toddler') AND order_index = 1)),
((SELECT id FROM assessment_domains WHERE code = 'autism_toddler'), 'How would you rate your child''s overall social interaction progress this month?', 'scale', '{"options": [{"value": 0, "label": "No Progress"}, {"value": 1, "label": "Minimal Progress"}, {"value": 2, "label": "Some Progress"}, {"value": 3, "label": "Good Progress"}, {"value": 4, "label": "Excellent Progress"}]}', 'toddler', 'parent', '{"follow_up_type": "overall_progress"}', 2, true, null),
((SELECT id FROM assessment_domains WHERE code = 'adhd_child'), 'Compared to last month, how is your child''s attention span during homework or chores?', 'scale', '{"options": [{"value": 0, "label": "Much Worse"}, {"value": 1, "label": "Worse"}, {"value": 2, "label": "No Change"}, {"value": 3, "label": "Better"}, {"value": 4, "label": "Much Better"}]}', 'child_adolescent', 'parent', '{"follow_up_type": "progress_tracking"}', 1, true, (SELECT id FROM assessment_questions WHERE domain_id = (SELECT id FROM assessment_domains WHERE code = 'adhd_child') AND order_index = 1));

-- Note: This is a sample of the comprehensive question bank
-- The full implementation would include all ~838 questions across all domains and age groups
-- Plus ~100 follow-up questions per domain/age group for longitudinal monitoring
